services:
  service:
    build:
      context: .

    environment:
      BFF_SERVICE_BASE_URL: "${BFF_SERVICE_BASE_URL:-http://localhost:9999}"

    volumes:
      - ./src:/package/src
      - ./tests:/package/tests

    ports:
      - "9998:8501"

    restart: unless-stopped
